rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head

services:
  - mysql

script: "bundle exec rake spec"

before_script:
  - mysql -e 'create database perfectqueue_test;'

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
